-- CreateEnum
CREATE TYPE "VisitType" AS ENUM ('INITIAL_VISIT', 'MEP_VISIT', 'PARTIAL_WORK_VISIT', 'SECONDARY_VISIT');

-- AlterTable
ALTER TABLE "Visit" ADD COLUMN "visitType" "VisitType" NOT NULL DEFAULT 'INITIAL_VISIT';
