-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAD_ASSIGNED_TO_YOU';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FACEBOOK_LEAD_SYNC_SUMMARY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VISIT_SCHEDULED_ADMIN';
