-- CreateEnum
CREATE TYPE "LeadStage" AS ENUM ('NEW', 'CONTACT_ATTEMPTED', 'NURTURING', 'VISIT_SCHEDULED', 'CLOSED');

-- CreateEnum
CREATE TYPE "LeadSubStatus" AS ENUM ('NUMBER_COLLECTED', 'NO_ANSWER', 'WARM_LEAD', 'FUTURE_CLIENT', 'SMALL_BUDGET', 'DEAD_LEAD', 'INVALID', 'NOT_INTERESTED', 'LOST');

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "stage" "LeadStage" NOT NULL DEFAULT 'NEW',
ADD COLUMN     "subStatus" "LeadSubStatus";
