-- BOQ assignment and requisition workflow states.
ALTER TYPE "LeadSubStatus" ADD VALUE IF NOT EXISTS 'BOQ_ASSIGNED' AFTER 'QUOTATION_CORRECTION';
ALTER TYPE "LeadSubStatus" ADD VALUE IF NOT EXISTS 'BOQ_WORKING' AFTER 'BOQ_ASSIGNED';
ALTER TYPE "LeadSubStatus" ADD VALUE IF NOT EXISTS 'BOQ_COMPLETED' AFTER 'BOQ_WORKING';
ALTER TYPE "LeadSubStatus" ADD VALUE IF NOT EXISTS 'BOQ_CORRECTION' AFTER 'BOQ_COMPLETED';
