-- CreateEnum
CREATE TYPE "AccountStatus" AS ENUM ('PENDING', 'PROCESSING', 'PARTIAL_PAID', 'FULL_PAID');

-- CreateEnum
CREATE TYPE "ExpenseCategory" AS ENUM ('OFFICE_RENT', 'SALARY', 'SALARY_ADVANCE', 'BONUS', 'ELECTRICITY_BILL', 'WATER_BILL', 'INTERNET_BILL', 'FOOD_ALLOWANCE', 'CLIENT_ENTERTAINMENT', 'PROMOTION', 'MOBILE_RECHARGE', 'OCTANE_FUEL', 'DONATION', 'BOARD_MATERIAL', 'PASTING_BILL', 'FARING', 'HPL', 'LINER', 'LUBER', 'ACRYLIC', 'HARDWARE', 'ELECTRIC_ITEM', 'LIGHTING', 'GLASS', 'TRANSPORT_COST', 'SITE_EXPENSE', 'FACTORY_PAYMENT', 'CARPENTER_PAYMENT', 'PAINT_MATERIALS', 'PAINT_PAYMENT', 'CEILING_PAYMENT', 'DOOR', 'PLUMBER_PAYMENT', 'TILES_PURCHASE', 'FOLDING_DOOR', 'GLASS_PROFILE', 'CIVIL_WORK', 'OTHERS');

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'VISIT_DUE_36H';
ALTER TYPE "NotificationType" ADD VALUE 'VISIT_DUE_48H';
ALTER TYPE "NotificationType" ADD VALUE 'VISIT_DUE_72H';

-- AlterEnum
ALTER TYPE "PaymentAccount" ADD VALUE 'BANK_EBL';
ALTER TYPE "PaymentAccount" ADD VALUE 'BANK_OTHER';

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN "accountStatus" "AccountStatus";

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN "serialNo" SERIAL NOT NULL,
ADD COLUMN "voucherNo" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Transaction_voucherNo_key" ON "Transaction"("voucherNo");
